project:
  type: website

website:
  title: "球形汤姆"
  # reader-mode: true
  # back-to-top-navigation: true
  page-navigation: true
  favicon: images/logo.jpg
  navbar:
    logo: images/logo.jpg
    search: true
    left:
      - href: index.qmd
        text: 主页
      - href: posts.qmd
        text: 博客
      - href: data.qmd
        text: 数据
      - href: code.qmd
        text: 代码
  page-footer: 
    background: light
    left: "Copyright 2024, 球形汤姆" 
    right: "Powered by Quarto!"

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    toc: true



